### ISSUE TITLE
Switching from .css to .styl renders differently on iOS

### ISSUE THREAD

**Issue by pipewrk** [frankdiox/OnsenUI-Meteor-ToDo#1]
This is the screenshot of the repository defaults css `imports` in `main.jsx`.

![image](https://cloud.githubusercontent.com/assets/780157/18153955/4c077074-7033-11e6-9a27-6c16a67e2521.png)

Perfect. Here's what happens when I swap it out with `blue-theme.styl`.

<img width="324" alt="screen shot 2016-08-31 at 3 23 22 pm" src="https://cloud.githubusercontent.com/assets/780157/18153987/80b30536-7033-11e6-8c29-8f247c95662c.png">

I think there are some styles missing in the stylus files, the toolbar is missing. I manually copied toolbar styles into my CSS, but that in turn leaves the "pending tasks" portion invisible.

I have tested on iPhone 4s simulator and an iPhone 6 device.

**Comment by frandiox** [comment]
@jasonnathan  Hi! Sorry for the late reply.
`onsen-css-components.css` is actually generated from the stylus files, so I doubt that there is an issue there. You need to import the stylus files and also `onsenui.css` file (that's not in the stylus). And of course it needs a stylus processor, but I guess you already have that.

For example, in Monaca CLI templates for React and Angular 2 we do it like this:

```
...
import React from 'react';
import ReactDOM from 'react-dom';
...

require('onsenui/stylus/blue-basic-theme.styl');
require('onsenui/css/onsenui.css');
```

**Comment by pipewrk** [comment]
Hey @frankdiox, I figured that bit out on my own :) However, considering the styles seem to be in their self-contained folders ie `{stylus,css}`, it seems counter-intuitive to depend on a css file when you decided to go stylus..

Just my ten cents. Thanks for the repo, learnt a whole bunch about Onsen through it.
