### ISSUE TITLE
TypeError: HTML.Raw is not a function

### ISSUE THREAD

**Issue by Meloncon** [frankdiox/OnsenUI-Meteor-ToDo#2]
Hi!

I downloaded this repo, unzipped it, and then did a `meteor npm install`, then `meteor`. I went to `localhost:3000` and got a blank white screen. The following was in the Chrome Dev Console:

<img width="460" alt="onsenui error" src="https://cloud.githubusercontent.com/assets/583455/18811553/a11fd74e-8281-11e6-8b2a-d1174f97d436.png">

I've tried various things, like `meteor update` and even swapped various versions of `onsenui` and `react-onsenui` in package.json. No luck getting it working, same error each time. I'm running macOS Sierra. Any thoughts? Is there anything else I can provide? Thanks!

-- Matt

**Comment by frandiox** [comment]
Thanks! It's fixed here https://github.com/OnsenUI/OnsenUI/issues/1599

I'll try to update the app and the blog post :)
